# Pre-commit hooks for code quality
# Install: pre-commit install
# Run manually: pre-commit run --all-files

repos:
  # Python hooks
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.0
    hooks:
      # Linter
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        files: ^python/
      # Formatter
      - id: ruff-format
        files: ^python/

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.0
    hooks:
      - id: mypy
        files: ^python/src/
        args: [--strict]
        additional_dependencies: []

  # Rust hooks
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
        args: ['--manifest-path', 'rust/Cargo.toml', '--']
      - id: clippy
        args: ['--manifest-path', 'rust/Cargo.toml', '--', '-D', 'warnings']

  # General file hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-toml
      - id: check-json
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: detect-private-key
      - id: mixed-line-ending
        args: ['--fix=lf']

  # Markdown and docs
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.17
    hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-gfm
          - mdformat-black
        files: ^docs/

  # Security checks
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.9
    hooks:
      - id: bandit
        args: ['-c', 'pyproject.toml']
        files: ^python/
        additional_dependencies: ['bandit[toml]']

  # Commit message checks
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.2.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []

# Configuration for specific hooks
default_language_version:
  python: python3.12
  rust: 1.70

# Exclude patterns
exclude: |
  (?x)^(
      \.git/|
      \.venv/|
      target/|
      pkg/|
      dist/|
      build/|
      .*\.lock$
  )
